#theme: jekyll-theme-merlot
theme: minima
title: circa 2111
description: Feel free to peruse then listen 

pages:
  - about.md


header_pages:
  - about.md
  - entho.html

disqus:
    shortname: disqus_FCVoWPUQuI

#
#google_analytics: UA-NNNNNNNN-N

show_excerpts: true           

gems:
  - jekyll-octicons
  - jekyll-asciinema