#theme: jekyll-theme-merlot

# https://github.com/jekyll/minima/tree/master/_layouts
theme: minima
title: circa 2111
description: Feel free to peruse then listen 

pages:
  - about.md


header_pages:
  - about.md
  - entho.html

disqus:
    shortname: disqus_FCVoWPUQuI

#
#google_analytics: UA-NNNNNNNN-N

show_excerpts: true           

# https://pages.github.com/versions/
gems:
  - jekyll-octicons

  # doesnt work on github pages
#   {% mermaid %}
# graph TD;
#     A-->B;
#     A-->C;
#     B-->D;
#     C-->D;
# {% endmermaid %}
# {% mermaid %}
# sequenceDiagram
#     participant Alice
#     participant Bob
#     Alice->>John: Hello John, how are you?
#     loop Healthcheck
#         John->>John: Fight against hypochondria
#     end
#     Note right of John: Rational thoughts <br/>prevail...
#     John-->>Alice: Great!
#     John->>Bob: How about you?
#     Bob-->>John: Jolly good!
# {% endmermaid %}

  - jekyll-mermaid
  
  # doesnt work on github pages
  - jekyll-asciinema   